In [35]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv('/content/train.csv')

In [38]:
df_subset.head()

        id        date  store_nbr               family  sales  onpromotion
0  2500888  2016-11-07          3  HOME AND KITCHEN II   41.0            0
1  2500889  2016-11-07          3      HOME APPLIANCES    0.0            0
2  2500890  2016-11-07          3            HOME CARE  625.0            8
3  2500891  2016-11-07          3           LADIESWEAR   40.0            0
4  2500892  2016-11-07          3      LAWN AND GARDEN    9.0            0

In [39]:
df.sample(5)

              id        date  store_nbr            family  sales  onpromotion
2387537  2387537  2016-09-04         49   LAWN AND GARDEN   15.0            0
401731    401731  2013-08-14         30  LIQUOR,WINE,BEER   45.0            0
2851998  2851998  2017-05-24         31       CELEBRATION    1.0            0
2117789  2117789  2016-04-06         30          HARDWARE    1.0            0
76463      76463  2013-02-12         54            BEAUTY    1.0            0

In [40]:
df['date'] = pd.to_datetime(df['date'])

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 11 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         datetime64[ns]
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
 6   year         int32
 7   month        int32
 8   day          int32
 9   dayofweek    int32
 10  is_weekend   int64
dtypes: datetime64[ns](1), float64(1), int32(4), int64(4), object(1)
memory usage: 206.1+ MB

In [42]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek
df['is_weekend'] = df['dayofweek'].isin([5,6]).astype(int)

In [44]:
df.drop(['id', 'date'],axis=1, inplace=True)

In [45]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['family'])
df['family'] = le.transform(df['family'])

In [47]:
df_subset = df.tail(500000).reset_index(drop=True)

In [48]:
from sklearn.model_selection import train_test_split

X = df_subset.drop('sales', axis=1)
y = df_subset['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle = False)

In [49]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, n_jobs=-1 , random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [50]:
from sklearn.metrics import root_mean_squared_error

y_pred = rf.predict(X_test)
rmse = root_mean_squared_error(y_test, y_pred)
print('RMSE:', rmse)

RMSE: 295.4905077143059